---

port: 4000
host: 0.0.0.0
safe: false

repository: qilinxue/qilinxue.github.io
### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "QiLin Xue"
keywords:    "QiLin Xue Volunteering Peel"
description: "My personal website"
source_link: "google.com"
favicon:     "img/favicon.ico"
touch_icon:  "img/QilinXue.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

### Contact Information
email:       "mailto:xueqilin@gmail.com"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#FCFCFC'
  blue:      '#7ABFEF'
  green:     '#35CE8D'
  purple:    '#827191'
  orange:    '#FDA50F'
  turquoise: '#5CA4B8'

kramdown:
  auto_ids:  false
